### ISSUE TITLE
I can't update the last card created in anki if i'm using https://killergerbah.github.io/asbplayer/

### ISSUE THREAD

**Issue by Lebannen01** [asbplayer/asbplayer#682]
So i mined a word with yomitan and i wanted to add a screenshot and the audio as i usually do using the "update the last card" function but when i press the shortcut to do so it just pauses the video and nothing happens. I'm on brave and i checked if it works on youtube and other sites and those are fine, the only place that gives me problems is https://killergerbah.github.io/asbplayer/ with local videos. I also tried it in chrome and there it works fine and there aren't any problems, and the settings are absolutely the same between chrome and brave. I really don't understand why it doesn't work and i would be really grateful if someone could help me, thanks in advance.

**Comment by killergerbah** [comment]
@Lebannen01 Can you check that this setting is enabled?

<img width="928" alt="Image" src="https://github.com/user-attachments/assets/93c24c84-96db-41f5-af6f-a289d37e8edf" />

And also can you send your developer console logs when the issue happens to you?

**Comment by killergerbah** [comment]
@Lebannen01 The PIPELINE_ERROR_DECODE error decode problem should be fixed now. As for `SecurityError: User activation is required` in theory it means that there was no user gesture on the page before you attempted to mine something, but I'm not sure how that is possible.

**Comment by erazavi** [comment]
I'm still seeing both errors. It's inconsistent on exactly how it happens, but I get some combination of:
Can't click around subtitles, get PIPELINE_ERROR_DECODE
Can't export subtitles, get PIPELINE or SecurityError
Occasionally, it will let me record and export 1 sentence and then goes back to not letting me export.

Haven't found a rhyme or a reason to this.

![Image](https://github.com/user-attachments/assets/90fe4c1c-9e1e-4d4f-a04d-0498780caa8b)
